\".    Part of liwc, a collection of tools for manipulating C source code
\".    Copyright (c) 1994-2003 Lars Wirzenius
\".
\".    This program is free software; you can redistribute it and/or modify
\".    it under the terms of the GNU General Public License, version 2, as 
\".    published by the Free Software Foundation.
\".
\".    This program is distributed in the hope that it will be useful,
\".    but WITHOUT ANY WARRANTY; without even the implied warranty of
\".    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
\".    GNU General Public License for more details.
\".
\".    You should have received a copy of the GNU General Public License along
\".    with this program; if not, write to the Free Software Foundation, Inc.,
\".    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH CHKTRI 1
.SH NAME
chktri \- check for trigraphs in C source code
.SH SYNOPSIS
chktri [file ...]
.SH "DESCRIPTION"
This program looks for lines containing trigraphs in C source code.
Trigraphs are a way to represent certain characters
in C source code as two question marks and a third character.
For example, a backslash could be represented as `??/'.
For a detail specification, see section 5.2.1.1 in the 
ISO 9899:1990 standard or any decent C book.
(You don't really want to know.)
.SH AUTHOR
Lars Wirzenius, liw@iki.fi.
