.TH LIWC 1
.SH NAME
liwc \- collection of programs to manipulate C source code
.SH "DESCRIPTION"
.B liwc
is a collection of programs to manipulate C source code.
.PP
.I ccmtcnvt
converts C++ comments to C comments.
.PP
.I chktri
checks for trigraphs.
.PP
.I cstr
prints out string literals.
.PP
.I entrigraph
converts C source to trigraphs, and
.I untrigraph
converts trigraphs to the single characters they represent.
.PP
.I rmccmt
removes comments.
.SH "SEE ALSO"
.IR ccmtcnvt (1),
.IR chktri (1),
.IR cstr (1),
.IR entrigraph (1),
.IR rmccmt (1),
.IR untrigraph (1).
.SH AUTHOR
Lars Wirzenius, liw@iki.fi.
