\".    Part of liwc, a collection of tools for manipulating C source code
\".    Copyright (c) 1994-2003 Lars Wirzenius
\".
\".    This program is free software; you can redistribute it and/or modify
\".    it under the terms of the GNU General Public License, version 2, as 
\".    published by the Free Software Foundation.
\".
\".    This program is distributed in the hope that it will be useful,
\".    but WITHOUT ANY WARRANTY; without even the implied warranty of
\".    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
\".    GNU General Public License for more details.
\".
\".    You should have received a copy of the GNU General Public License along
\".    with this program; if not, write to the Free Software Foundation, Inc.,
\".    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH UNTRIGRAPH 1
.SH NAME
untrigraph \- remove trigraphs from C source code
.SH SYNOPSIS
untrigraph [file ...]
.SH "DESCRIPTION"
untrigraph converts trigraphs into their single character equivalents.
.PP
See the entrigraph(1) manual page for a description of trigraphs.
.SH "SEE ALSO"
entrigraph(1)
.SH AUTHOR
Lars Wirzenius, liw@iki.fi.
